### ISSUE TITLE
How about support for Find 11?

### ISSUE THREAD

**Issue by defsteph** [episerver/PowerSlice#15]
I get how it adds extra workload on the team, but not updating Powerslice along with Find prevents the upgrade process. Maybe consider merging the products?

**Comment by kdelacreme** [comment]
We're just waiting for your pull request, @defsteph

**Comment by davidwinslow** [comment]
@defsteph yes that would be a great help!

**Comment by kdelacreme** [comment]
Thanks @defsteph :)

**Comment by davidwinslow** [comment]
awesome @defsteph

**Comment by kdelacreme** [comment]
https://nuget.episerver.com/en/OtherPages/Package/?packageId=PowerSlice&packageVersion=2.1.3.0
