### ISSUE TITLE
Compatibility with EPiserver.CMS.UI version 10.1.0 +

### ISSUE THREAD

**Issue by dotcentric-samb** [episerver/PowerSlice#22]
The latest version of powerslice i can find is v2.1.4. this has a dependency on EPiServer.CMS.UI versions ranging between 8 and 10 but the latest version of EPiServer.CMS.UI is 10.1.0

**Comment by dotcentric-samb** [comment]
any news on this?
i can see that there is a commit in the branch 'cms-10-compatibility' that should fix the issue but i assume it needs testing? I'm currently upgrading an episerver site to version 10 but if it breaks poweslice then the work will have to be delayed.

**Comment by thorhj** [comment]
Hi @dotcentric-samb,

I am not associated with PowerSlice, but I can see that the cms-10-compatibility" branch only has a change for the dependency in the NuGet specification - no other changes. I can tell you that I have installed the current version from NuGet on Episerver 10 (ignoring the dependency constraint) without any problems so far.

**Comment by kdelacreme** [comment]
Version 2.1.5 was built Tuesday this week and will hit the nuget feed on Tuesday next week.

**Comment by thorhj** [comment]
@kdelacreme Version 2.1.5 (available on the NuGet feed now) is not compatible with Episerver 10+.

**Comment by dotcentric-samb** [comment]
@thorhj thanks for the tip - i hadn't realised that you can ignore dependencies when installing packages. i managed to get powerslice working.

@kdelacreme I also noticed that the only change in the latest release is the version number - as thorhj says, the branch doesn't look like it was checked in. I think it would be a good idea to keep this ticket open until the fix is tested and release or someone else might create a duplicate.
