### ISSUE TITLE
Support for CMS 11

### ISSUE THREAD

**Issue by defsteph** [episerver/PowerSlice#29]
Looks like I'm the only one using PowerSlice :)

PR #28

**Comment by folkertsj** [comment]
No no sir.  I am using it as well.  Just forked to upgrade and you beat me too it :)

**Comment by lockevn** [comment]
we are working on it. Built and are testing new package with CMS11.

**Comment by lockevn** [comment]
Solved https://github.com/episerver/PowerSlice/pull/30
